//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCWCFUygulamasi.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/AdventureWorksService")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IServiceAdventureWorks")]
    public interface IServiceAdventureWorks {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAdventureWorks/GetData", ReplyAction="http://tempuri.org/IServiceAdventureWorks/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAdventureWorks/GetData", ReplyAction="http://tempuri.org/IServiceAdventureWorks/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAdventureWorks/GetAddressDataByID", ReplyAction="http://tempuri.org/IServiceAdventureWorks/GetAddressDataByIDResponse")]
        string GetAddressDataByID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAdventureWorks/GetAddressDataByID", ReplyAction="http://tempuri.org/IServiceAdventureWorks/GetAddressDataByIDResponse")]
        System.Threading.Tasks.Task<string> GetAddressDataByIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAdventureWorks/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IServiceAdventureWorks/GetDataUsingDataContractResponse")]
        MVCWCFUygulamasi.ServiceReference1.CompositeType GetDataUsingDataContract(MVCWCFUygulamasi.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAdventureWorks/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IServiceAdventureWorks/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<MVCWCFUygulamasi.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(MVCWCFUygulamasi.ServiceReference1.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceAdventureWorksChannel : MVCWCFUygulamasi.ServiceReference1.IServiceAdventureWorks, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceAdventureWorksClient : System.ServiceModel.ClientBase<MVCWCFUygulamasi.ServiceReference1.IServiceAdventureWorks>, MVCWCFUygulamasi.ServiceReference1.IServiceAdventureWorks {
        
        public ServiceAdventureWorksClient() {
        }
        
        public ServiceAdventureWorksClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceAdventureWorksClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAdventureWorksClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAdventureWorksClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public string GetAddressDataByID(int id) {
            return base.Channel.GetAddressDataByID(id);
        }
        
        public System.Threading.Tasks.Task<string> GetAddressDataByIDAsync(int id) {
            return base.Channel.GetAddressDataByIDAsync(id);
        }
        
        public MVCWCFUygulamasi.ServiceReference1.CompositeType GetDataUsingDataContract(MVCWCFUygulamasi.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<MVCWCFUygulamasi.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(MVCWCFUygulamasi.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
